version: '3'

services:

  db:
    image: postgres
    container_name: db_app
    ports:
      - '5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pg_data1:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build: .
    tty: true
    env_file:
      - .env
    container_name: educational_modules
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code

volumes:
  pg_data1: