# Generated by Django 4.2.7 on 2023-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название модуля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание модуля')),
                ('amount', models.IntegerField(default=70000, verbose_name='цена модуля')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=30, verbose_name='название модуля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание модуля')),
                ('amount', models.IntegerField(default=70000, verbose_name='цена модуля')),
            ],
            options={
                'verbose_name': 'Образовательный модуль',
                'verbose_name_plural': 'Образовательные модули',
            },
        ),
    ]
